### ISSUE TITLE
"No tests found" Error

### ISSUE THREAD

**Issue by chaehwanli** [chaehwanli/mockito-testcode#1]
Caused by: org.gradle.api.tasks.testing.TestExecutionException: No tests found for given includes: [com.example.mytest.CalculatorTest](--tests filter)
	at org.gradle.api.tasks.testing.AbstractTestTask.handleCollectedResults(AbstractTestTask.java:515)
	at org.gradle.api.tasks.testing.AbstractTestTask.executeTests(AbstractTestTask.java:508)
	at org.gradle.api.tasks.testing.Test.executeTests(Test.java:689)

**Comment by chaehwanli** [comment]
ref : https://stackoverflow.com/questions/30474767/no-tests-found-for-given-includes-error-when-running-parameterized-unit-test-in
